name: Build

on: [pull_request]

env:
  APP_NAME: 'Software Defined Haptics'
  IDF_VERSION: 'v5.5.1'
  IDF_COMPONENT_MANAGER: "1" # whether to enable the component manager or not
  FLASH_TOTAL_OVERRIDE: '2097152' # 2MB flash app partition for main app

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        build:
        - path: '.'
          name: 'test-stand'
          target: esp32s3
          command: |
            idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.test_stand" build
        - path: '.'
          name: 'motorgo'
          target: esp32s3
          command: |
            idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.motorgo" build

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build Examples
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.IDF_VERSION }}
        target: ${{ matrix.build.target }}
        path: ${{ matrix.build.path }}
        command: ${{ matrix.build.command }}

    - name: Determine Size Delta
      uses: esp-cpp/esp-idf-size-delta@v1
      # only run this on the motorgo build
      if: ${{ matrix.build.name == 'motorgo' }}
      with:
        app_name: ${{ env.APP_NAME }}
        app_path: '.'
        idf_target: ${{ matrix.build.target }}
        idf_version: ${{ env.IDF_VERSION }}
        idf_component_manager: ${{ env.IDF_COMPONENT_MANAGER }}
        flash_total_override: ${{ env.FLASH_TOTAL_OVERRIDE }}
