name: Build and Package Main

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

env:
  APP_NAME: 'Software Defined Haptics'
  IDF_VERSION: 'v5.5.1'
  IDF_COMPONENT_MANAGER: "1" # whether to enable the component manager or not
  FLASH_TOTAL_OVERRIDE: '2097152' # 2MB flash app partition for main app

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      matrix:
        build:
        - name: 'tinys3_test_stand'
          path: '.'
          target: esp32s3
          command: |
            idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.test_stand" build
        - name: 'motorgo'
          path: '.'
          target: esp32s3
          command: |
            idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.motorgo" build

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build Main Code
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.IDF_VERSION }}
        target: ${{ matrix.build.target }}
        path: ${{ matrix.build.path }}
        command: ${{ matrix.build.command }}

    - name: Upload Build Outputs
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.build.name }}-build-artifacts
        path: |
          build/*.bin
          build/*.elf
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/flasher_args.json
          build/flash_args

    - name: Zip up files for upload to release
      if: ${{ github.event.release && github.event.action == 'published' }}
      shell: bash
      run: |
        cd build
        zip -r ../${{ matrix.build.name }}.zip *.bin *.elf bootloader/bootloader.bin partition_table/partition-table.bin flasher_args.json flash_args
        cd ..

    - name: Attach files to release
      uses: softprops/action-gh-release@v2
      if: ${{ github.event.release && github.event.action == 'published' }}
      with:
        files: ${{ matrix.build.name }}.zip

    - name: Determine Size Delta
      # only run this on the motorgo build and if the release is published
      if: ${{ github.event.release && github.event.action == 'published' && matrix.build.name == 'motorgo' }}
      uses: esp-cpp/esp-idf-size-delta@v1
      with:
        app_name: ${{ env.APP_NAME }}
        app_path: "."
        idf_target: ${{ matrix.build.target }}
        idf_version: ${{ env.IDF_VERSION }}
        idf_component_manager: ${{ env.IDF_COMPONENT_MANAGER }}
        flash_total_override: ${{ env.FLASH_TOTAL_OVERRIDE }}
        post_comment: 'false'

  package:
    name: Package the binaries into an executables for Windows, MacOS, and Linux (Ubuntu)
    needs: build
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build: ['tinys3_test_stand', 'motorgo']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: esp-cpp/esp-packaged-programmer-action@v1.0.5
        with:
          zipfile-name: ${{ matrix.build }}-build-artifacts
          programmer-name: 'software-defined-haptics-${{ matrix.build }}_programmer'
